name: Update Docker Hub Description
on:
  push:
    paths:
      - '**/README.md'
jobs:
  workingdir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: changed-files
        uses: tj-actions/changed-files@v11.9
        with:
          files: |
            README.md$
      - name: Get Updated Directories
        id: changed-dirs
        run: |
          RESULT=
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            RESULT="$(dirname $file) $RESULT"
          done
          RESULT=$(echo $RESULT | sed 's/ /\n/g' | sort | uniq | xargs)
          RESULT=$(echo $RESULT | jq -Rcr 'split(" ")')
          RESULT="{\"dir\":$RESULT}"
          echo "::set-output name=all::$RESULT"
    outputs:
      all: ${{ steps.changed-dirs.outputs.all }}
  build:
    needs: workingdir
    strategy:
      matrix: ${{ fromJson(needs.workingdir.outputs.all) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import env variables
        run: |
            if [ -f ${{ matrix.dir }}/Dockervar ]; then
              grep -v ^# ${{ matrix.dir }}/Dockervar >> ${GITHUB_ENV} || true
            fi
      - name: Update Docker Hub Description
        if: ${{ env.DOCKER_REPO != '' }}
        uses: wangkexiong/dockerhub-description@e0d81b64103dac1bba18d6e29ed158f9ede5c295
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}
          readme-filepath: ${{ matrix.dir }}/README.md

